spring:
  application:
    name: TeluskoSpringSecurityTutorial
  data:
    mongodb:
      database: Spring-React-Poc-DB
      uri: ${MONGODB_URI}
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8080
  address: 0.0.0.0
  ssl:
    enabled: false

growhub:
  jwtexpirationtime: 604800000 # 1000 * 60 * 60 * 24 * 7 = 604800000 ms = 7 days
  signalingserver:
    url: http://signaling-server-service.default.svc.cluster.local:8181