apiVersion: apps/v1
kind: Deployment
metadata:
  name: signaling-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signaling-server
  template:
    metadata:
      labels:
        app: signaling-server
    spec:
      containers:
        - name: signaling-server
          image: ghcr.io/allaskevin/signaling-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8181
          env:
            - name: NODE_ENV
              value: "production"
      imagePullSecrets:
        - name: ghcr-secret
