apiVersion: v1
kind: Service
metadata:
  name: signaling-server-service
  labels:
    app: signaling-server
spec:
  type: ClusterIP
  selector:
    app: signaling-server
  ports:
    - name: http
      port: 8181
      targetPort: 8181
      protocol: TCP
